"""padron solo dni: nombre/apellido nullable, sin curso/division

Revision ID: 36f52354d4f2
Revises: e830fbc6cad9
Create Date: 2026-05-28 20:12:28.854237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f52354d4f2'
down_revision: Union[str, Sequence[str], None] = 'e830fbc6cad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('persona', 'apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('persona', 'division')
    op.drop_column('persona', 'curso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('curso', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('division', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('persona', 'apellido',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('persona', 'nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
