"""password_hash en persona (login staff)

Revision ID: 3f85751c01a7
Revises: 36f52354d4f2
Create Date: 2026-05-28 23:02:18.591883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f85751c01a7'
down_revision: Union[str, Sequence[str], None] = '36f52354d4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'password_hash')
    # ### end Alembic commands ###
