"""qr_token en persona (credencial alumno)

Revision ID: 88614e5a22cc
Revises: 3f85751c01a7
Create Date: 2026-05-28 23:21:43.010028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88614e5a22cc'
down_revision: Union[str, Sequence[str], None] = '3f85751c01a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('qr_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_persona_qr_token'), 'persona', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_qr_token'), table_name='persona')
    op.drop_column('persona', 'qr_token')
    # ### end Alembic commands ###
