"""esquema inicial

Revision ID: e830fbc6cad9
Revises: 
Create Date: 2026-05-28 19:27:28.169280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e830fbc6cad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.Enum('alumno', 'docente', 'encargado', 'admin', name='rol'), nullable=False),
    sa.Column('curso', sa.String(length=20), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=160), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('foto_embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'activo', 'suspendido', name='estado_persona'), nullable=False),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=True)
    op.create_table('titulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('editorial', sa.String(length=160), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulo_isbn'), 'titulo', ['isbn'], unique=True)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('libro', 'netbook', 'adaptador', 'mapa', 'otro', name='tipo_material'), nullable=False),
    sa.Column('tipo_codigo', sa.Enum('isbn_copia', 'interno', name='tipo_codigo'), nullable=False),
    sa.Column('titulo_id', sa.Integer(), nullable=True),
    sa.Column('numero_copia', sa.Integer(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'prestado', 'en_reparacion', 'baja', name='estado_material'), nullable=False),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['titulo_id'], ['titulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno', name='uq_material_codigo_interno'),
    sa.UniqueConstraint('titulo_id', 'numero_copia', name='uq_material_titulo_copia')
    )
    op.create_table('sesion',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_persona_id'), 'sesion', ['persona_id'], unique=False)
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('prestado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('devuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condicion_devolucion', sa.Enum('ok', 'observacion', name='condicion_devolucion'), nullable=True),
    sa.Column('checklist_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('encargado_prestamo_id', sa.Integer(), nullable=True),
    sa.Column('encargado_devolucion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encargado_devolucion_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['encargado_prestamo_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamo_material_id'), 'prestamo', ['material_id'], unique=False)
    op.create_index(op.f('ix_prestamo_persona_id'), 'prestamo', ['persona_id'], unique=False)
    op.create_table('incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.Enum('baja', 'media', 'alta', name='severidad'), nullable=False),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidente_material_id'), 'incidente', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidente_material_id'), table_name='incidente')
    op.drop_table('incidente')
    op.drop_index(op.f('ix_prestamo_persona_id'), table_name='prestamo')
    op.drop_index(op.f('ix_prestamo_material_id'), table_name='prestamo')
    op.drop_table('prestamo')
    op.drop_index(op.f('ix_sesion_persona_id'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_table('material')
    op.drop_index(op.f('ix_titulo_isbn'), table_name='titulo')
    op.drop_table('titulo')
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.drop_table('persona')
    # ### end Alembic commands ###
